# **TITANIC DATA SURVIVAL PREDICTION**

In [ ]:
import torch.nn as nn
import torch.optim as optim
import pandas as pd
import numpy as np
from torch.utils.data import DataLoader,TensorDataset
import torch

# **LOAD DATA**

In [ ]:
titanic=pd.read_csv('/Titanic.csv')

In [ ]:
titanic.head()

      sex   age  sibsp  parch     fare embarked  class    who  alone  survived
0    male  22.0      1      0   7.2500        S  Third    man  False         0
1  female  38.0      1      0  71.2833        C  First  woman  False         1
2  female  26.0      0      0   7.9250        S  Third  woman   True         1
3  female  35.0      1      0  53.1000        S  First  woman  False         1
4    male  35.0      0      0   8.0500        S  Third    man   True         0

In [ ]:
titanic.columns

Index(['sex', 'age', 'sibsp', 'parch', 'fare', 'embarked', 'class', 'who',
       'alone', 'survived'],
      dtype='object')

In [ ]:
titanic.shape

(891, 10)

# **DATA PREPROCESSING**

# NULL VALUE HANDLING

In [ ]:
(titanic.isnull()==True).sum()

sex           0
age         177
sibsp         0
parch         0
fare          0
embarked      2
class         0
who           0
alone         0
survived      0
dtype: int64

In [ ]:
titanic["age"].fillna(titanic["age"].mean(),inplace=True)

/tmp/ipykernel_5768/2475312687.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  titanic["age"].fillna(titanic["age"].mean(),inplace=True)

In [ ]:
(titanic.isnull()==True).sum()

sex         0
age         0
sibsp       0
parch       0
fare        0
embarked    2
class       0
who         0
alone       0
survived    0
dtype: int64

In [ ]:
titanic['embarked'].fillna(titanic['embarked'].mode()[0], inplace=True)

/tmp/ipykernel_5768/3984909897.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  titanic['embarked'].fillna(titanic['embarked'].mode()[0], inplace=True)

In [ ]:
titanic.isnull().sum()

sex         0
age         0
sibsp       0
parch       0
fare        0
embarked    0
class       0
who         0
alone       0
survived    0
dtype: int64

In [ ]:
titanic.drop(columns=["who"],inplace=True)

# ENCODE STRING VALUES

In [ ]:
titanic.columns

Index(['sex', 'age', 'sibsp', 'parch', 'fare', 'embarked', 'class', 'alone',
       'survived'],
      dtype='object')

In [ ]:
titanic=pd.get_dummies(titanic,columns=['sex','embarked','alone','class'])

In [ ]:
titanic.head()

,age,sibsp,parch,fare,survived,sex_female,sex_male,embarked_C,embarked_Q,embarked_S,alone_False,alone_True,class_First,class_Second,class_Third
0,22.0,1,0,7.2500,0,False,True,False,False,True,True,False,False,False,True
1,38.0,1,0,71.2833,1,True,False,True,False,False,True,False,True,False,False
2,26.0,0,0,7.9250,1,True,False,False,False,True,False,True,False,False,True
3,35.0,1,0,53.1000,1,True,False,False,False,True,True,False,True,False,False
4,35.0,0,0,8.0500,0,False,True,False,False,True,False,True,False,False,True

In [ ]:
print(titanic.columns)

Index(['age', 'sibsp', 'parch', 'fare', 'survived', 'sex_female', 'sex_male',
       'embarked_C', 'embarked_Q', 'embarked_S', 'alone_False', 'alone_True',
       'class_First', 'class_Second', 'class_Third'],
      dtype='object')

In [ ]:
titanic = titanic.astype(int)

In [ ]:
titanic.head()

,age,sibsp,parch,fare,survived,sex_female,sex_male,embarked_C,embarked_Q,embarked_S,alone_False,alone_True,class_First,class_Second,class_Third
0,22,1,0,7,0,0,1,0,0,1,1,0,0,0,1
1,38,1,0,71,1,1,0,1,0,0,1,0,1,0,0
2,26,0,0,7,1,1,0,0,0,1,0,1,0,0,1
3,35,1,0,53,1,1,0,0,0,1,1,0,1,0,0
4,35,0,0,8,0,0,1,0,0,1,0,1,0,0,1

# HANDLE DUPLICATES

In [ ]:
titanic.drop(columns=["sex_male","class_Third"],inplace=True)

In [ ]:
titanic.head()

,age,sibsp,parch,fare,survived,sex_female,embarked_C,embarked_Q,embarked_S,alone_False,alone_True,class_First,class_Second
0,22,1,0,7,0,0,0,0,1,1,0,0,0
1,38,1,0,71,1,1,1,0,0,1,0,1,0
2,26,0,0,7,1,1,0,0,1,0,1,0,0
3,35,1,0,53,1,1,0,0,1,1,0,1,0
4,35,0,0,8,0,0,0,0,1,0,1,0,0

In [ ]:
titanic.drop(columns=["embarked_S","alone_False"],inplace=True)

In [ ]:
titanic.head()

,age,sibsp,parch,fare,survived,sex_female,embarked_C,embarked_Q,alone_True,class_First,class_Second
0,22,1,0,7,0,0,0,0,0,0,0
1,38,1,0,71,1,1,1,0,0,1,0
2,26,0,0,7,1,1,0,0,1,0,0
3,35,1,0,53,1,1,0,0,0,1,0
4,35,0,0,8,0,0,0,0,1,0,0

# **SETTING TARGET AND INPUT**

In [ ]:
x=titanic.drop(columns=["survived"])

In [ ]:
x

,age,sibsp,parch,fare,sex_female,embarked_C,embarked_Q,alone_True,class_First,class_Second
0,22,1,0,7,0,0,0,0,0,0
1,38,1,0,71,1,1,0,0,1,0
2,26,0,0,7,1,0,0,1,0,0
3,35,1,0,53,1,0,0,0,1,0
4,35,0,0,8,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...
886,27,0,0,13,0,0,0,1,0,1
887,19,0,0,30,1,0,0,1,1,0
888,29,1,2,23,1,0,0,0,0,0
889,26,0,0,30,0,1,0,1,1,0
890,32,0,0,7,0,0,1,1,0,0

In [ ]:
y=titanic["survived"]

In [ ]:
x=torch.tensor(x.values,dtype=torch.float32)
y=torch.tensor(y.values,dtype=torch.long)

In [ ]:
x = (x - x.mean(dim=0)) / x.std(dim=0)

In [ ]:
x.shape,y.shape

(torch.Size([891, 10]), torch.Size([891]))

In [ ]:
dataset=TensorDataset(x,y)

In [ ]:
dataloader=DataLoader(dataset=dataset,shuffle=True,batch_size=64)

In [ ]:
input_dim=x.shape[1]
hidden_dim=24
output_dim=2

# **MODEL CREATION**

In [ ]:
model=nn.Sequential(
    nn.Linear(in_features=input_dim,out_features=hidden_dim),
    nn.ReLU(),
    nn.Linear(in_features=hidden_dim,out_features=output_dim)
)

In [ ]:
optimizer=optim.Adam(model.parameters(),lr=0.005)
loss_fn = nn.CrossEntropyLoss()

# **TRAINING LOOP**

In [ ]:
epochs=200
for epoch in range(epochs):
  for i,(inputs,labels) in enumerate(dataloader):
    outputs=model(inputs)
    loss=loss_fn(outputs,labels)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
  if epoch%10==0:
    print(f"Epoch {epoch+1}/{epochs}, Loss: {loss.item()}")

Epoch 1/200, Loss: 0.5597115159034729
Epoch 11/200, Loss: 0.24375393986701965
Epoch 21/200, Loss: 0.40358567237854004
Epoch 31/200, Loss: 0.46280890703201294
Epoch 41/200, Loss: 0.32282188534736633
Epoch 51/200, Loss: 0.3396075665950775
Epoch 61/200, Loss: 0.2732585370540619
Epoch 71/200, Loss: 0.43565675616264343
Epoch 81/200, Loss: 0.259897381067276
Epoch 91/200, Loss: 0.3277709484100342
Epoch 101/200, Loss: 0.33104753494262695
Epoch 111/200, Loss: 0.3212020993232727
Epoch 121/200, Loss: 0.31181854009628296
Epoch 131/200, Loss: 0.2908565402030945
Epoch 141/200, Loss: 0.3320474922657013
Epoch 151/200, Loss: 0.3695240914821625
Epoch 161/200, Loss: 0.29159632325172424
Epoch 171/200, Loss: 0.2370305359363556
Epoch 181/200, Loss: 0.33857622742652893
Epoch 191/200, Loss: 0.38498300313949585

# **MODEL EVALUATION**

In [ ]:
correct = 0
total = 0

with torch.no_grad():
    for inputs, labels in dataloader:
        outputs = model(inputs)
        _, predicted = torch.max(outputs, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

print(f"Accuracy: {100 * correct / total:.2f}%")

Accuracy: 86.76%

In [ ]:
with torch.no_grad():
    outputs = model(x)
    _, predicted = torch.max(outputs, 1)

In [ ]:
print("Predicted:", predicted[:10])
print("Actual   :", y[:10])

Predicted: tensor([0, 1, 0, 1, 0, 0, 0, 0, 1, 1])
Actual   : tensor([0, 1, 1, 1, 0, 0, 0, 0, 1, 1])